### ISSUE TITLE
Create a library of single Entity pipelines

### ISSUE THREAD

**Issue by jde** [coralproject/atoll#36]
__Challenge__: We want to have many interesting "Measurable" fields attached to each Entity (currently Comments, Users and Assets). These measurable fields can be composed into various searches, data viz elements, sorts, etc...

Each pipeline should be implemented into atoll.

I have set up a library file here to track the pipelines:
https://github.com/coralproject/atoll/blob/master/docs/library.md

**Comment by colinmegill** [comment]
Fantastic @ftzeng

**Comment by ftzeng** [comment]
It sounds like we need to implement a documentation endpoint that describes the metrics that atoll computes, for which entities, and with their datatypes and ranges

e.g. `/1.0/metric_docs`

**Comment by riley** [comment]
- talked to Francis. He's going to get us a schema of metrics from atoll that will describe ranges, and datatypes for information that you can extract from atoll. This will be delivered as json, and I suggest we cache it in xenia under a job that updates it every so often. 

request for clarification: is this dropdown controlling the data viz a list of `query_sets` or a list of metrics from atoll, or both?

**Comment by jde** [comment]
I'm not clear on the statement "this dropdown controlling the data viz".  Here are the factors at play as I see them:

* there's going to be a filter box with several fields.  These serve to limit the dataset returned.  These values will be used in all the relevant query_sets served by xenia.  (for now as query params, eventually as Pre Pipeline hook objects https://github.com/coralproject/xenia/issues/35)
* each dataviz we do will need to know what query_set it is going to pull from via internal configuration
* Every _entity_ returned by a query_set will have an object full of metrics attached to it.  We may have interfaces _within_ data visualizations that show how those various metrics stack up (aka, multiple lines on a chart.)

**Comment by jde** [comment]
Concerning the documentation endpoint, the idea here is to feed ordinary language explanations of what each metric consists of/means to the FE so that they can be displayed via some sort of tooltip.  @riley @colinmegill

**Comment by colinmegill** [comment]
@jde I'm going to create a series of mocks to explain the dropdown controlling data viz - back to you soon

**Comment by ftzeng** [comment]
@jde @colinmegill @riley implemented the autodoc endpoint, it's in PR #42. take a look if you have a sec, if no one has any objections I'll merge it in and deploy it this afternoon

**Comment by ftzeng** [comment]
oh also a heads up - the json it will return is slightly different than what you're getting now. instead of a list, it returns a dict/hashtable where the keys are the entity name

**Comment by frnsys** [comment]
@colinmegill @riley this commit https://github.com/coralproject/atoll/commit/7ba9d9eaa61555af38a1d8f09cba69aaaa22cac1 (not yet merged) changes the valid type for some metrics, instead of

```
"valid": {
    "type": "range",
    "min": 0,
    "max": null,
    "min_inclusive": true,
    "max_inclusive": false
}
```

you'll just get:

```
"valid": {
    "type": "nonnegative"
}
```

since it seemed like a lot of unnecessary information.

similarly, I'm thinking of changing:

```
"valid": {
    "type": "range",
    "min": 0,
    "max": 1,
    "min_inclusive": true,
    "max_inclusive": true
}
```

to the more concise:

```
"valid": {
    "type": "probability"
}
```

what do you think?

**Comment by jde** [comment]
This is a really interesting thought.  It boils down to "who owns the logic behind the semantics."  Two arguments:

- The front end should own the logic because the front end is responsible for the individual components that use the granular properties.  If we have atoll provide those properties, then we would be adding a dependency to update atoll if we need to add more concepts to the types. 

- Atoll should deliver all the concepts for the types because these concepts are descriptions of the data that atoll is sending.  This will allow for many front end applications to consume atoll data with full type information without needing to reimplement what each type means.

My thought is that Atoll should send verbose type information to the extent that it _describes the data_.  This way any consumer of atoll can know everything about the data that is coming across.  Anything that _describes interface components_ should not come from atoll.  

The verbosity of repeating the full description of each type for each bit of data can be mitigated by using the more concise {type: xxx} syntax that references a small library object included in the response.

**Comment by frnsys** [comment]
> The verbosity of repeating the full description of each type for each bit of data can be mitigated by using the more concise {type: xxx} syntax that references a small library object included in the response.

That sounds great - I'll just use the more concise descriptions on atoll's side and switch over to the more verbose description for what's sent to clients.

**Comment by frnsys** [comment]
We have some metrics for each entity and endpoints to compute them, so I'll close this now
