### ISSUE TITLE
Split coral-atoll and darwin from atoll?

### ISSUE THREAD

**Issue by frnsys** [coralproject/atoll#39]
Currently, this project repo contains three sub-projects:

- `atoll`, where the pipeline and pipeline service functionality is defined
- `coral`(-atoll), where the specific coral atoll application is defined
- `darwin`, where the experimental metric-designing frontend is defined

I think these should be broken out into separate projects, otherwise a lot of different things get mixed up - any thoughts @jde?

**Comment by ftzeng** [comment]
Or the more sensible option might be to break out `atoll` into a separate project (with a different name), and make this repo only the coral instance of atoll.

**Comment by jde** [comment]
I agree that we are going to need some way for individual companies to write and store their own pipelines.  Also, we are hoping to have an open set of pipelines that can be developed in a common space and imported / exported into private repos.

Let's readdress this for after our first partner beta (Feb 2016).
