### ISSUE TITLE
historical binning of data

### ISSUE THREAD

**Issue by frnsys** [coralproject/atoll#43]
The motivation for computing time-binned metrics (as proposed below) is three-fold:

- provides data easily represented as histograms for the frontend
- reduces the amount of data sent to atoll/that atoll needs to process
- with "rolling" metrics, behavior from long ago has less influence on a user's metrics today

We have to decide the bin size - for example, let's say it's one month.

To compute metrics for an entity, `pillar` (or whichever service is the go-between atoll and the database) sends only the following to atoll:

- the entity's data for only the current month, starting from the first until the current date
- the entity's metrics computed for the last n months

`atoll` then computes and responds with the following:

- month-to-date metrics for the user as some kind of rolling average (e.g. an [exponential moving average](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average))

`pillar` stores these metrics for each past month, which are easily used by the frontend for a time-series histogram.

**Comment by jde** [comment]
This is a great proposal Francis.  This should vastly reduce redundant data being passed while achieving just about all the metrics we would want.  

As you mentioned, one month may or may not be the right duration.  This should be configurable so we can tune.  For example, we may want to do daily binning for Assets, which generally only have activity for a number of days.  

Also, we should do an analysis to see if there are any metrics that binning would make impossible.  The only one I can think of is concepts surrounding 'medians', which are not crucial.

+1 for proceeding with the binning methodology.

**Comment by frnsys** [comment]
Cool - for configuring the bin size, do you see that as something that happens once at the start or something that can be changed later on? The only challenge with making it changeable later on is that it would have to retroactively recompute all the previous time bins.

Yeah, unfortunately this approach makes certain metrics trickier, but I think it supports almost anything we'd want.

Ultimately, the way I see atoll handling this is that it will be totally agnostic to the time bin size (that's something that would be handled on pillar's side). It would just look for `previous_time_bin_metrics` or something like that in the submitted data.

**Comment by frnsys** [comment]
Oh - also, earlier we discussed computing some "activity" or "consistency" metric for a user, this is something that would be possible with this approach (for example, we can look at average differences in commenting frequency between time bins)
