### ISSUE TITLE
"network" metrics

### ISSUE THREAD

**Issue by frnsys** [coralproject/atoll#45]
There's some interest in analyses that do things like identify latent communities among commenters; these aren't really "metrics" but are insightful. For the most part they are probably best served by a graph database (simple queries over a graph database would likely give interesting results) but some could be handled by atoll.

For example, if for each comment entity we also have a field with the `user_id` of the parent comment, we could do the following:

- % of a user's replies to unique users - this lets us know if the user tends only to interact with a small and consistent group of people, or if they interact with the community more broadly.
- top n most interacted with users - who is this user talking to the most, and what % of their replies are to that user?

**Comment by jde** [comment]
These are great insights.  I'd love to see these attached to each user document.  

We have discussed experimenting with blueprint as a way of accessing our mongo collections via graph concepts:

https://github.com/tinkerpop/blueprints/wiki

This looks like a perfect excuse to look more deeply at what blueprints can offer.  

Alternatively, we're discussing abstracting the db layer from pillar, which will allow us to set up writes to both mongo and something like neo4j.  Maintaining two databases, however, adds significant cost/complexity.
